# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: '5e814e0b-3dbf-4b24-9af3-238547ec9c70'
  imageRepository: 'fyh'
  containerRegistry: 'originregistry.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'
  
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: test_and_build
  displayName: Test and build
  jobs:  
  - job: Test
    displayName: Unit tests
    pool:
      vmImage: $(vmImageName)
    steps:
    - script: sudo mkdir /etc/sawtooth && sudo chmod 777 /etc/sawtooth &&
              sudo mkdir /var/lib/sawtooth && sudo chmod 777 /var/lib/sawtooth &&
              sudo mkdir /var/log/sawtooth && sudo chmod 777 /var/log/sawtooth
      displayName: Create sawtooth folders

    - script: sudo apt update
      displayName: Update repo

    - script: sudo apt install -y pkg-config gcc libsecp256k1-dev libzmq3-dev
      displayName: Install packages

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.7'

    - script: python -m pip install -r requirements.txt
      displayName: 'Install requirements'

    - script: git submodule update --init --recursive
      displayName: Git get submodules

    - script: pytest -m unittest --cov-report=term-missing --cov-fail-under=90 --cov=src/origin_handlers
      displayName: 'Run tests'

    - script: pytest -m integrationtest
      displayName: 'Run tests'

  - job: Docker release
    displayName: Docker Release
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
