apiVersion: v1
kind: Service
metadata:
  name: hyperledger-service
  namespace: project-origin
spec:
  ports:
  - port: 80
    targetPort: 8008
  selector:
    app: hyperledger-sawtooth-deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hyperledger-sawtooth-deployment
  namespace: project-origin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hyperledger-sawtooth-deployment
  template:
    metadata:
      labels:
        app: hyperledger-sawtooth-deployment
    spec:
      containers:

      - name: hyperledger-sawtooth-rest-api-container
        image: hyperledger/sawtooth-rest-api:1.2.4
        ports:
        - containerPort: 8008
        command:
        - sawtooth-rest-api
        args:
        - -C
        - tcp://127.0.0.1:4004
        - --bind
        - 0.0.0.0:8008

      - name: hyperledger-sawtooth-validator-container
        image: hyperledger/sawtooth-validator:1.2.4
        command:
        - bash
        args:
        - -c
        - "sawadm keygen && \
          sawtooth keygen my_key && \
          sawset genesis -k /root/.sawtooth/keys/my_key.priv && \
          sawset proposal create \
            -k /root/.sawtooth/keys/my_key.priv \
            sawtooth.consensus.algorithm.name=Devmode \
            sawtooth.consensus.algorithm.version=0.1 \
            -o config.batch && \
          sawadm genesis config-genesis.batch config.batch && \
          sawtooth-validator -vv \
            --endpoint tcp://127.0.0.1:8800 \
            --bind component:tcp://0.0.0.0:4004 \
            --bind network:tcp://0.0.0.0:8800 \
            --bind consensus:tcp://0.0.0.0:5050 \
          "

      - name: sawtooth-settings-tp
        image: hyperledger/sawtooth-settings-tp:1.2.4
        command:
        - bash
        args:
        - -c
        - "settings-tp -vv -C tcp://127.0.0.1:4004"

      - name: hyperledger-sawtooth-devmode-engine-container
        image: hyperledger/sawtooth-devmode-engine-rust:1.2
        command: ["devmode-engine-rust", "-C", "tcp://127.0.0.1:5050"]

      - name: hyperledger-sawtooth-ledger-tp-container
        image: projectorigin/ledger_tp:latest
        env:
        - name: 'LEDGER_URL'
          value: 'tcp://127.0.0.1:4004'
