---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hyperledger-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hyperledger-deployment
  template:
    metadata:
      labels:
        app: hyperledger-deployment
    spec:
      containers:

        - name: hyperledger-sawtooth-rest-api-container
          image: hyperledger/sawtooth-rest-api:1.2.4
          ports:
            - containerPort: 8008
          command:
            - sawtooth-rest-api
          args:
            - -C
            - tcp://127.0.0.1:4004
            - --bind
            - 0.0.0.0:8008

        - name: sawtooth-settings-tp
          image: hyperledger/sawtooth-settings-tp:1.2.4
          command:
          - bash
          args:
          - -c
          - "settings-tp -vv -C tcp://127.0.0.1:4004"

        - name: hyperledger-sawtooth-devmode-engine-container
          image: hyperledger/sawtooth-devmode-engine-rust:1.2
          command: ["devmode-engine-rust", "-vv", "-C", "tcp://127.0.0.1:5050"]

        - name: hyperledger-sawtooth-ledger-tp-container
          image: projectorigin/ledger_tp:{{ .Values.tag }}
          env:
          - name: 'LEDGER_URL'
            value: 'tcp://127.0.0.1:4004'

        - name: hyperledger-sawtooth-validator-container
          image: hyperledger/sawtooth-validator:1.2.4
          ports:
          - containerPort: 8800
          - containerPort: 4004
          - containerPort: 5050
          command:
          - bash
          args:
          - -c
          - "if [ -f /etc/sawtooth/keys/validator.pub ]; then \
                rm -f /var/lib/sawtooth/genesis.batch ; \
              else \
                sawadm keygen && \
                sawtooth keygen my_key && \
                sawset genesis -k /root/.sawtooth/keys/my_key.priv && \
                sawset proposal create \
                  -k /root/.sawtooth/keys/my_key.priv \
                  sawtooth.consensus.algorithm.name=Devmode \
                  sawtooth.consensus.algorithm.version=0.1 \
                  -o config.batch && \
                sawadm genesis config-genesis.batch config.batch; \
              fi && \
              sawtooth-validator -vv \
                --endpoint tcp://127.0.0.1:8800 \
                --bind component:tcp://0.0.0.0:4004 \
                --bind network:tcp://0.0.0.0:8800 \
                --bind consensus:tcp://0.0.0.0:5050 \
              "
          volumeMounts:
            - name: ledger-key
              mountPath: /etc/sawtooth/keys
            - name: ledger-storage
              mountPath: /var/lib/sawtooth
            
      volumes:
        - name: ledger-key
          persistentVolumeClaim:
            claimName: ledger-key-disk

        - name: ledger-storage
          persistentVolumeClaim:
            claimName: ledger-storage-disk